#!/usr/bin/env bash
# make provision — delete .env and recreate it from .env.example with freshly
# autogenerated secrets (POSTGRES_PASSWORD, PGE_JWT_SECRET, PGE_VAULT_KEY).
# DESTRUCTIVE: any hand-tuned values in the old .env (port, memory tuning, replication
# settings, a customized POSTGRES_DB, etc.) are discarded. A backup is left at .env.bak.
set -euo pipefail
cd "$(dirname "$0")/.."

ENV_FILE=".env"
TEMPLATE_FILE=".env.example"
BACKUP_FILE=".env.bak"

[ -f "$TEMPLATE_FILE" ] || { echo "ERROR: $TEMPLATE_FILE not found." >&2; exit 1; }

if [ -f "$ENV_FILE" ]; then
  cp "$ENV_FILE" "$BACKUP_FILE"
  echo "Backed up existing $ENV_FILE to $BACKUP_FILE (gitignored)."
  rm -f "$ENV_FILE"
fi

cp "$TEMPLATE_FILE" "$ENV_FILE"

# In-place KEY=VALUE substitution that preserves line position + comments (portable —
# no sed -i, whose -i flag differs between macOS/BSD and GNU). Every key here is
# guaranteed to exist in the freshly-copied template.
replace_in_place() {  # replace_in_place KEY VALUE
  local key="$1" val="$2"
  awk -v k="$key" -v v="$val" 'BEGIN{FS="="} $1==k{$0=k"="v} {print}' "$ENV_FILE" \
    > "$ENV_FILE.tmp" && mv "$ENV_FILE.tmp" "$ENV_FILE"
}

# openssl rand -hex 32 for all three: the only generation method this repo already
# documents (verbatim-required for PGE_VAULT_KEY — pgsodium needs exactly 32 bytes /
# 64 hex chars), and hex output has no ':'/'@'/'/' that could break a
# postgres://user:pass@host connection URI.
NEW_POSTGRES_PASSWORD="$(openssl rand -hex 32)"
NEW_JWT_SECRET="$(openssl rand -hex 32)"
NEW_VAULT_KEY="$(openssl rand -hex 32)"

replace_in_place POSTGRES_PASSWORD "$NEW_POSTGRES_PASSWORD"
replace_in_place PGE_JWT_SECRET    "$NEW_JWT_SECRET"
replace_in_place PGE_VAULT_KEY     "$NEW_VAULT_KEY"

echo "Regenerated: POSTGRES_PASSWORD, PGE_JWT_SECRET, PGE_VAULT_KEY in $ENV_FILE."
echo "(Not printed here — view with: grep -E '^(POSTGRES_PASSWORD|PGE_JWT_SECRET|PGE_VAULT_KEY)=' .env)"
echo
echo "NOTE: PGE_JWT_SECRET is only seeded on a FRESH data volume (first-boot init)."
echo "If the 'pgeverything' volume already has data, run 'make clean' first, or"
echo "'make up' will keep using the OLD secret for that one."
echo
echo "Next: make up"
